/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface Loloof64ChessboardStencil {
        /**
          * True if and only if the black side is at bottom.
         */
        "reversed": boolean;
    }
}
declare global {
    interface HTMLLoloof64ChessboardStencilElement extends Components.Loloof64ChessboardStencil, HTMLStencilElement {
    }
    var HTMLLoloof64ChessboardStencilElement: {
        prototype: HTMLLoloof64ChessboardStencilElement;
        new (): HTMLLoloof64ChessboardStencilElement;
    };
    interface HTMLElementTagNameMap {
        "loloof64-chessboard-stencil": HTMLLoloof64ChessboardStencilElement;
    }
}
declare namespace LocalJSX {
    interface Loloof64ChessboardStencil {
        /**
          * Game ended by checkmate. Detail property (eventValue.detail) is true if and only if white has been checkmated.
         */
        "onCheckmate"?: (event: CustomEvent<boolean>) => void;
        /**
          * Game ended by 50 moves rule.
         */
        "onFiftyMovesRule"?: (event: CustomEvent<void>) => void;
        /**
          * Game ended by insufficient material.
         */
        "onInsufficientMaterial"?: (event: CustomEvent<void>) => void;
        /**
          * Game ended by stalemate.
         */
        "onStalemate"?: (event: CustomEvent<void>) => void;
        /**
          * Game ended by threeFoldRepetition.
         */
        "onThreeFoldRepetition"?: (event: CustomEvent<void>) => void;
        /**
          * True if and only if the black side is at bottom.
         */
        "reversed"?: boolean;
    }
    interface IntrinsicElements {
        "loloof64-chessboard-stencil": Loloof64ChessboardStencil;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "loloof64-chessboard-stencil": LocalJSX.Loloof64ChessboardStencil & JSXBase.HTMLAttributes<HTMLLoloof64ChessboardStencilElement>;
        }
    }
}
